language: node_js

node_js:
  - "node"

services:
  - docker

sudo: required

env:
  - PORT=5005 MONGODB_URI=mongodb://ct-auth-db:27017/ct-auth-db FIREBASE_API_KEY=test GOOGLE_SERVICE_FILE=service-account.json GOOGLE_SERVICE_CREDS="{}" GENUX_TOKEN_SECONDS_EXPIRATION=60

install:
  - npm install

before_script:
  - docker run --rm -d -p 27017:27017 --name="test" mongo:3.6.4

script:
  - npm run test:integration

after_script:
  - docker stop test