version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-auth-server:latest
    environment:
      - PORT=5006
    ports:
      - "5006:5006"
    depends_on:
      - ct-auth-db

  ct-auth-db:
    image: mongo:3.6.4
