version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-auth-server:latest
    env_file:
      - .env
    environment:
      - PORT=5006
      - MONGODB_URI=mongodb://ct-auth-db:27017/ct-auth-db
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - ct-auth-db

  ct-auth-db:
    image: mongo:3.6.4
